apiVersion: v1
kind: ConfigMap
metadata:
  name: converter-configmap
data:
  MP3_QUEUE: "mp3"
  VIDEO_QUEUE: "video"
  MONGODB_URI: "mongodb://nasi:nasi1234@43.205.138.214:30005/mp3s?authSource=admin" #nodeip:nodeport
