apiVersion: v1
kind: Secret
metadata:
  name: converter-secret
stringData:
  GMAIL_ADDRESS: "devopsp10@gmail.com" #enter your email to get the id
  GMAIL_PASSWORD: "gbzn aels cbnu mzwe"
  PLACEHOLDER: "NONE"
type: Opaque